# DATABASE CONFIG
spring.datasource.url=jdbc:postgresql://localhost:5432/ecommerce_db
spring.datasource.username=postgres
spring.datasource.password=root

# EMAIL CONFIG
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=prachii8826@gmail.com
spring.mail.password=your_app_password

# JWT SECRET
jwt.secret=your_secret_key