spring.application.name=backend

# DATABASE CONFIG
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO}
spring.jpa.show-sql=true

server.error.include-stacktrace=never

# SENDGRID CONFIG
sendgrid.api.key=${SENDGRID_API_KEY}
sendgrid.from.email=${SENDGRID_FROM_EMAIL}

# JWT SECRET
jwt.secret=your_secret_key

spring.datasource.hikari.maximum-pool-size=2
spring.datasource.hikari.minimum-idle=1
spring.jpa.open-in-view=false
server.tomcat.threads.max=20
server.tomcat.threads.min-spare=5